/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univel;

import javax.swing.table.TableModel;
import br.univel.ClienteModel;
import java.util.List;
import br.univel.Cliente;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tgamer
 */
public class TelaPrincipal extends javax.swing.JFrame {
    H2Con h2 = new H2Con();

    List<Cliente> listaClt = new ArrayList<>();
    List<Produto> listaPrd = new ArrayList<>();
    
    TelaPrincipal(List<Cliente> lista, List<Produto> listap) {
        initComponents();
        try {
            h2.abrirConexao();
            listaPrd = h2.readProdutoBanco();
            listaClt = h2.readClienteBanco();
            h2.fecharConexao();
            //this.listaClt = lista;
            //this.listaPrd = listap;
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jbCliente = new javax.swing.JButton();
        jbProduto = new javax.swing.JButton();
        jlwhatever = new javax.swing.JLabel();
        jlOperacoes = new javax.swing.JLabel();
        jbCadastroProduto = new javax.swing.JButton();
        jbCadastrarCliente = new javax.swing.JButton();
        jbVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(792, 400));

        jspTabela.setMaximumSize(new java.awt.Dimension(1000000, 1000000));
        jspTabela.setVerifyInputWhenFocusTarget(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspTabela.setViewportView(tabela);

        jbCliente.setText("Popula Clientes");
        jbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbClienteMouseClicked(evt);
            }
        });

        jbProduto.setText("Popula Produto");
        jbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbProdutoMouseClicked(evt);
            }
        });

        jlwhatever.setText("Leitura de Dados do Banco");

        jlOperacoes.setText("Operações");

        jbCadastroProduto.setText("Cadastro Produto");
        jbCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastroProdutoMouseClicked(evt);
            }
        });

        jbCadastrarCliente.setText("Cadastrar Cliente");
        jbCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastrarClienteMouseClicked(evt);
            }
        });

        jbVendas.setText("Tela de Vendas");
        jbVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVendasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jlwhatever)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlOperacoes)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbCliente)
                        .addGap(45, 45, 45)
                        .addComponent(jbProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jbCadastroProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCadastrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbVendas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlwhatever)
                    .addComponent(jlOperacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCliente)
                    .addComponent(jbProduto))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastroProduto)
                    .addComponent(jbCadastrarCliente)
                    .addComponent(jbVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbClienteMouseClicked
        try {
            preencheTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbClienteMouseClicked

    private void jbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbProdutoMouseClicked
        try {
            preencheTabelaProduto();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbProdutoMouseClicked

    private void jbCadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastroProdutoMouseClicked
       CadastrarProduto();
    }//GEN-LAST:event_jbCadastroProdutoMouseClicked

    private void jbVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVendasMouseClicked
        TelaVendas();
    }//GEN-LAST:event_jbVendasMouseClicked

    private void jbCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarClienteMouseClicked
        TelaCadastroCliente();
    }//GEN-LAST:event_jbCadastrarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    protected void CadastrarProduto(){
       this.setVisible(false); 
       TelaCadastroProduto tcp = new TelaCadastroProduto(this);
        
    }
    
    protected void TelaVendas(){
       this.setVisible(false); 
       TelaVendas tcp = new TelaVendas(this);
       tcp.setVisible(true);
        
    }
    
    private void TelaCadastroCliente() {
        this.setVisible(false);
        TelaCadastroCliente tcc = new TelaCadastroCliente(this);
        tcc.setVisible(true);
    }
    
    protected void preencheTabela() throws SQLException {
                h2.abrirConexao();
                listaClt = h2.readClienteBanco();

		//ClienteParser parserc = new ClienteParser();
		//List<Cliente> listaClt = parserc.getCliente(listac);
                //List<Cliente> listaClt = h2.readClienteBanco();
		ClienteModel model = new ClienteModel(listaClt);
		tabela.setModel(model);

    }
    
    protected void preencheTabelaProduto() throws SQLException {
                h2.abrirConexao();
                listaPrd = h2.readProdutoBanco();
		//ArquivoReader reader = new ArquivoReader();
		//List<String> listap = reader.lerArquivo();

		//ProdutoParser parser = new ProdutoParser();
		//List<Produto> listaPrd = parser.getProduto(listap);

		ProdutoModel model = new ProdutoModel(listaPrd);
		tabela.setModel(model);

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaPrincipal().setVisible(true);
            }
        });
        
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrarCliente;
    private javax.swing.JButton jbCadastroProduto;
    private javax.swing.JButton jbCliente;
    private javax.swing.JButton jbProduto;
    private javax.swing.JButton jbVendas;
    private javax.swing.JLabel jlOperacoes;
    private javax.swing.JLabel jlwhatever;
    private javax.swing.JScrollPane jspTabela;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    
}
